name: Continuous Integration
on: [push, pull_request]

jobs:
  CI:
    runs-on: ubuntu-22.04
    defaults:
      run:
        shell: bash -l {0}
    strategy:
      matrix:
        gnu-compiler-version:  [10, 11, 12]
    env:
      FC: gfortran-${{ matrix.gnu-compiler-version }}
      CC: gcc-${{ matrix.gnu-compiler-version }}
      FCFLAGS: "-ffree-line-length-none -m64 -std=f2008 -march=native -fbounds-check -finit-real=nan -g -DRTE_USE_CBOOL"
      NFHOME: /home/runner/netcdf-fortran
    steps:
    - name: Update system packages
      run: sudo apt-get update
    ############################################################################
    #
    # Compilers....
    #    #
    - name: install compilers
      run: sudo apt-get install gfortran-${{ matrix.gnu-compiler-version }} gcc-${{ matrix.gnu-compiler-version }}

    ############################################################################
    #
    # Netcdf C and Fortran
    #
    - name: Install HDF5 library
      run: |
        sudo apt-get install libhdf5-dev libcurl4-gnutls-dev hdf5-helpers libnetcdf-dev
        dpkg -L libhdf5-dev libnetcdf-dev

    # Would be great to encode version info
    - name: cache-netcdf-fortran
      id: cache-netcdf-fortran
      uses: actions/cache@v3
      with:
        path: /home/runner/netcdf-fortran
        key: netcdf-fortran-4.5.3-${{ runner.os }}-${{ matrix.fortran-compiler }}

    - name: Build NetCDF Fortran library
      # Here too it would be nice to use the environment to specify netcdf-c location
      env:
        CPPFLAGS: -I/home/runner/netcdf-c/include
        LDFLAGS: -L/home/runner/netcdf-c/lib
        LD_LIBRARY_PATH: /home/runner/netcdf-c/lib
        FCFLAGS: -fPIC
      if: steps.cache-netcdf-fortran.outputs.cache-hit != 'true'
      run: |
        echo ${TEST}
        ${FC} --version
        git clone https://github.com/Unidata/netcdf-fortran.git --branch v4.5.3
        cd netcdf-fortran
        echo ${CPPFLAGS}
        ./configure --prefix=${NFHOME}
        make -j
        sudo make install
  ############################################################################
    # Checks out repository under $GITHUB_WORKSPACE
    - name: Check out host repo
      uses: actions/checkout@v3
      with:
        path: rte-ecckd

    - name: Check out RTE repo
      uses: actions/checkout@v3
      with:
        repository: earth-system-radiation/rte-rrtmgp
        path: rte-rrtmgp

    - name: Environmental variables
      run: echo "RRTMGP_ROOT=${GITHUB_WORKSPACE}/rte-rrtmgp"        >> $GITHUB_ENV

    - name: Make RTE library
      run: |
        ls 
        ${FC} --version
        cd ${RRTMGP_ROOT}
        make libs

    - name: Make RTE-ECCKD
      env:
        FCFLAGS: "-ffree-line-length-none -m64 -std=f2008 -march=native -fbounds-check -finit-real=nan -g -DRTE_USE_CBOOL -I/${RRTMGP_ROOT}/build"
      run: |
        cd rte-ecckd
        make

